
#Will start the gateway server @8081
server:
  port: 8081

#Application Name
spring:
  application:
    name: zuul-server

#Eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Ribbon is auto integrated with Zuul and for this exercise we are not using that.
ribbon:
  eureka:
    enabled: false

#Zuul routes. Here for /student-service path, we are routing to localhost:8090 with extra path after that.
zuul:
  routes:
    student-service:
      url: http://localhost:8098