server:
  port: 9098    #port number

spring:
  application:
    name: school-service    #service name

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
logging:
  level:
    com.charter.eurekaClientSchoolService: DEBUG

#For Hystrix dashbord
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream