server:
  port: 9093
spring:
  application:
    name: ribbon-server

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com:
      charter:
        ribbonServer: DEBUG